name: hello
description: A new Flutter project.
version: 1.0.0
#environment:
#  sdk: ">=2.1.0 <3.0.0"

dependencies:
#  flutter_webview_plugin: "^0.1.6"
  web_socket_channel: ^1.0.15
  objectdb: ^1.0.1
  mutex: ^1.0.1
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  path_provider: ^0.4.1
  cupertino_icons: ^0.1.2
  flare_flutter: ^1.5.5
  connectivity: '0.4.4'
  device_info: '0.4.0+3'
  oktoast:
  permission_handler:
  flutter_gallery_assets:
#  flutter_webview_plugin: 0.3.8
  video_player: 0.10.2+3
  gbk2utf8:
  image:
  webview_flutter:
  platform_view_test:
    path: 'plugins/platform_view_test'
  file_uploader:
    path: plugins/file_uploader
#  exportable: "^0.1.0"

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/videos/
    - assets/images/
    - assets/flrs/


  fonts:
    - family: rokkittFamily
      fonts :
      - asset: assets/fonts/Rokkitt.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
